function(check_compiling_with_clang result_var)
	if(NOT DEFINED ${result_var})
		if(CMAKE_C_COMPILER_ID MATCHES "CLANG" AND CMAKE_CXX_COMPILER_ID MATCHES "CLANG")
			set(${result_var} true PARENT_SCOPE)
		else()
			set(${result_var} false PARENT_SCOPE)
		endif()
	endif()
endfunction(check_compiling_with_clang)

function(check_compiling_with_gcc result_var)
	if(NOT DEFINED ${result_var})
		if(CMAKE_C_COMPILER_ID MATCHES "GNU" AND CMAKE_C_COMPILER_ID MATCHES "GNU")
			set(${result_var} true PARENT_SCOPE)
		else()
			set(${result_var} false PARENT_SCOPE)
		endif()
	endif()
endfunction(check_compiling_with_gcc)

